### ISSUE TITLE
Is it possible to format the text?

### ISSUE THREAD

**Issue by aeri** [SeppPenner/Serilog.Sinks.Telegram#11]
I would like to be able to apply styles as specified in the Telegram style guide (https://core.telegram.org/bots/api#html-style) but I can't get.

I saw something mentioned about it in #8 but I'm not sure if any progress was made on it.

When i log something like:
```C#
Serilog.Log.Write(LogEventLevel.Warning, $"<b>bold</b>");
```
I receive in my chat:
```&lt;b&gt;bold&lt;/b&gt;```

Is it possible to apply formatting in any way with this library?

Thank you.

**Comment by SeppPenner** [comment]
I can provide a switch that allows to format the messages as you like (something like a bool `allowHtmlFormatting = true`. In general, the special HTML chars are HTML encoded (as you already figured out) to avoid formatting issues in Telegram.

**Comment by aeri** [comment]
That would be great, as far as I see HTML is not currently supported, but is it possible to use now other format techniques like Markdown?

**Comment by SeppPenner** [comment]
I had some serious trouble with Markdown and MarkdownV2 formatting (To make it look good in Telegram). Please don't ask me what exactly was the problem because I don't really remember. I only know that it was really complicated to construct and escape the characters.

So, if you ask me, the boolean flag (Like a 'I know what I'm doing' flag) is the best option for that and doesn't affect the other users if the default is set to `false`.

**Comment by SeppPenner** [comment]
With the next version, you can now use the option `useCustomHtmlFormatting` and set it to `true`. I have added a test where this is shown --> Check out: https://github.com/serilog-contrib/Serilog.Sinks.Telegram.Alternative/blob/761e2185a7381c1c2ad29de99e06acb8d91110e5/src/Serilog.Sinks.Telegram.Tests/TestSink.cs#L455

**Comment by aeri** [comment]
Great, thank you very much for the fast support and maintenance of the library :)
